[WIP] Legg til react-i18next for flerspråk støtte
1-fredrikstad/sangbok pull request #30
Opened 2021-02-26 13:18 UTC by amunds1

Closes #29

2021-02-26 15:39 UTC, kharann requested changes

2021-02-26 15:39 UTC, kharann commented on package.json
> +  "dependencies": {
Skal dette være i rot? Kan hende det er smartere å splitte typ react-i18 til react-i18 sin mappe osv

2021-02-26 17:12 UTC, amunds1 commented on package.json
> +  "dependencies": {
Du har rett, skal fikse det

2021-02-27 11:43 UTC, kharann approved these changes

2021-02-27 11:44 UTC, merged